spring.application.name=module-24
server.port=8080

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

gemini.api.key=PASTE_THE_GEMINI_API_KEY_HERE_TO_RUN